[Distributed][auto-parallel] Sharding Specification and rule discovery
hidet-org/hidet pull request #336
Opened 2023-07-31 00:38 UTC by soodoshll

This PR tries to implement step 1) and 3) mentioned in https://github.com/hidet-org/hidet/issues/335#issuecomment-1656568711

It contains an example of automatically discovering the sharding rules of all operators in resnet model, which involves dynamic batch size. You can run it with 

```python -m hidet.distributed.partition.rule``` 

Now we only support discovering 1D partitions.

The rule discovery process is basically to enumerate all possible input-sharding specifications and check their validity. The checking takes two steps:
1. Shape check: it will generate a sharded version of input tensors and re-forward the op to get the new output tensors. Then it will try to align the new output with the original whole output tensors, in order to find which output dimensions are sharded. For example, if the input $A$ is an 8x8 matrix, the op is $sin$, and we want to shard the first dimension of $A$ into 2 partitions, then it will generate an input shard with shape 4x8, and get the output shape 4x8, and we know that the first dimension of the output is also shared. 
2. Data dependency check. The validity of the shape check does not guarantee correctness. For example, if we have an 8x8 matrix $A$, and the op is $softmax$, then sharding along the second dimension gives the correct shape but wrong results, because the denominator of $softmax$ depends on the complete second dimension. So we analyze the range of data the output depends on, and the sharding is valid only if **the output shard only depends on the input shard**. For example, any shard of $A+1$ only depends on the same shard of $A$, so it is valid. We trace the indexing expressions(`TensorElement`) from `fcompute` of all outputs, to get the range of input indices that are accessed. And then we use Z3 SMT solver to check if any accessed input indices are out of the shard boundary. If not, the sharding is valid.

Note that even data dependency does not guarantee correctness completely (if the op plays tricks), but I find it can cover most of the ops I met. Though we still need to test it more thoroughly.

I can add more details about it to the RFC.

cc @yaoyaoding @xinli-git

2023-07-31 16:45 UTC, yaoyaoding commented
Hi @soodoshll,

Can I know the main purpose of the z3 solver? 

Because we also have a bound analyzer as well as an arthimatic simplifier in hidet, is any limitation of our internal analyzer and simpilifer? 

We need to be cautious when introducing new dependency, thus more justification is needed when introducing a new one.

2023-07-31 20:29 UTC, yaoyaoding commented
Make sense. For different sequence length, the best partition strategy might be different. Thus, we do need to optimize for some specific input size and then use the found stragegy for all sequence length.

2023-08-01 04:30 UTC, yaoyaoding commented
Hi @soodoshll, ping me when the PR is ready to be reviewed. Thanks!

2023-08-02 19:53 UTC, yaoyaoding commented
Hi @soodoshll, thanks for the update!

After you finish the whole pipeline, you can split it into several PRs and @xinli-git and I can help to review.

2023-08-03 20:32 UTC, yaoyaoding requested changes
Thanks @soodoshll !

I left some comments. In general, it is highly suggested to add the type annotation for the class fields and function parameters so that we do not need to check the usage of the class/function to know what it expects. It will reduce the time needed to understand the code and review. We might need to write this to our developer guide.

The current discovery algorithm only tries to find the sharding rule for 1-d mesh. It is better to write a module-level comment to briefly describe what we have done, what's the assumption and what's the limitation.

2023-08-03 20:32 UTC, yaoyaoding commented on python/hidet/distributed/partition/rule.py
> +    resnet_test()
Add some tests for the shard rule searching in `tests/distributed/partition/test_shard_rule.py`.

2023-08-04 16:19 UTC, xinli-git reviewed
I am still going through the code to understand the sharding rules better but posting some comments first. 

Feel free to merge without me once Yaoyao thinks it looks good :)

2023-08-04 16:19 UTC, xinli-git commented on python/hidet/distributed/partition/rule.py
> +        except (ValueError, RuntimeError, AssertionError, IndexError):
how do we arrive at these exceptions? I assume through trial and error?

2023-08-04 16:19 UTC, xinli-git commented on python/hidet/distributed/partition/shard.py
> +        if i != shard_dim:
regarding the -1 vs None, I think the code would be cleaner with None meaning not sharded and avoid -1. For example, here,  we can just check if shard_dim is None and be more explicit.

2023-08-04 18:45 UTC, xinli-git commented on python/hidet/distributed/partition/rule.py
> +                [TensorShardSpec(len(t.shape)) for t in op.inputs], [TensorShardSpec(len(t.shape)) for t in op.outputs]
a sorry, my bad

2023-08-04 18:51 UTC, yaoyaoding commented on python/hidet/distributed/partition/rule.py
> +        super().__init__()
Hi @xinli-git , the current writing looks fine. This function does not require any explicit ordering of calling its parent classes' init method. The default one `super().__init__()` will call them in MRO order and it works as we expected. Explicitly calling some parent class's init method might ignore some other parent classes and is error prone.

2023-08-04 18:53 UTC, yaoyaoding commented on python/hidet/distributed/partition/shard.py
> +    None or negative numbers will be treated as not to shard on this dimension
The latter one has better readability in this case to me :)

2023-08-04 19:05 UTC, yaoyaoding approved these changes
It looks good to me now. 

Feel free to merge after fixing the existing comments. Thanks @soodoshll !

2023-08-04 19:05 UTC, yaoyaoding commented on python/hidet/distributed/partition/rule.py
> +            index_rewriter.visit(o)
```suggestion
        index_rewriter = IndexRewriter()
        index_rewriter.visit(self.op.task.outputs)
        self.valid = all(isinstance(out, GridCompute) for out in self.op.task.outputs)
```

2023-08-04 19:26 UTC, merged